# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f29f64c5b2691cbb2cfc06cdec1e3fc782541a8cdc28f5a45c1836ebd75420d80d0b256c67fcd2d288e60343235b8dd9286fc79adad9daa0cad1edc133b5acfb

test:
  secret_key_base: 9b387d790227a1cc00c54db74d37a8da90f06d0da69c6106e010afd3a54422d780566d2f357b2275e6cfeda53028728e8fe43edb014df56e96ed60bb42aa3b74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
